In [1]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B= ',np.add(A,B))
print('A-B= ',np.substract(A,B))

A+B=  [5 5 3]


AttributeError: module 'numpy' has no attribute 'substract'

In [2]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B= ',np.add(A,B))
print('A-B= ',np.subtract(A,B))

A+B=  [5 5 3]
A-B=  [-3 -1  3]


In [3]:
import numpy as np
tmp = [1,2,3]
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B= ',np.add(A,B))
print('A-B= ',np.subtract(A,B))

A+B=  [5 5 3]
A-B=  [-3 -1  3]


In [4]:
tmp

[1, 2, 3]

In [5]:
C = np.array([1,2,3],[1,1,1])
D = np.array([4,3,9,9],[1,1,2,2,],[4,2,1,1])
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.marmul(C,D))
print('        C@D    = ',np.marmul(C,D))

print('np.multiply(D,D) = ',np.mulyiply(D,D))
print('          D*D    = ', D*D)

TypeError: data type not understood

In [6]:
C = np.array([1,2,3],
             [1,1,1])
D = np.array([4,3,9,9],
             [1,1,2,2,],
             [4,2,1,1])
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.marmul(C,D))
print('        C@D    = ',np.marmul(C,D))

print('np.multiply(D,D) = ',np.mulyiply(D,D))
print('          D*D    = ', D*D)

TypeError: data type not understood

In [7]:
C = np.array([[1,2,3],
             [1,1,1]])
D = np.array([[4,3,9,9],
             [1,1,2,2,],
             [4,2,1,1]])
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.marmul(C,D))
print('        C@D    = ',np.marmul(C,D))

print('np.multiply(D,D) = ',np.mulyiply(D,D))
print('          D*D    = ', D*D)

np.dot(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]


AttributeError: module 'numpy' has no attribute 'marmul'

In [8]:
C = np.array([[1,2,3],
             [1,1,1]])
D = np.array([[4,3,9,9],
             [1,1,2,2,],
             [4,2,1,1]])
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.matmul(C,D))
print('        C@D    = ',np.matmul(C,D))

print('np.multiply(D,D) = ',np.mulyiply(D,D))
print('          D*D    = ', D*D)

np.dot(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
        C@D    =  [[18 11 16 16]
 [ 9  6 12 12]]


AttributeError: module 'numpy' has no attribute 'mulyiply'

In [9]:
C = np.array([[1,2,3],
             [1,1,1]])
D = np.array([[4,3,9,9],
             [1,1,2,2,],
             [4,2,1,1]])
#矩阵的乘积
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.matmul(C,D))
print('        C@D    = ',np.matmul(C,D))
#元素与元素相乘
print('np.multiply(D,D) = ',np.multiply(D,D))
print('          D*D    = ', D*D)

np.dot(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
        C@D    =  [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D) =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
          D*D    =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


In [10]:
C.shape
D.shape


(3, 4)

In [11]:
D.shape

(3, 4)

In [12]:
C.shape

(2, 3)

In [13]:
#元素与元素相乘
A = np.array([1,2,3])
print('np.multiply(A,A) = ',np.multiply(A,A))
print('          A*A    = ', A*A)

np.multiply(A,A) =  [1 4 9]
          A*A    =  [1 4 9]


In [14]:
C@D

array([[18, 11, 16, 16],
       [ 9,  6, 12, 12]])

In [15]:
A*A

array([1, 4, 9])

In [ ]:
# np.dot() 与np.matmul()的区别